# Generated by Django 3.2.6 on 2021-08-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
                ('count', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('happiness', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('fear', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.user')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.user')),
            ],
        ),
    ]
